<!DOCTYPE html>
<html><head>
    <title>littleboy97学习笔记</title><meta charset="utf-8">
    
<link rel="stylesheet" href="/css/main.css">
<!-- 引入配置文件 -->
    
<link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.min.css">
<!-- 字体图片库 -->
    
<link rel="stylesheet" href="/lib/highlight/styles/atom-one-dark.css">
<!-- 代码高亮库 -->
<meta name="generator" content="Hexo 6.3.0"></head>
<body>
    <div id="main">
        <aside id="aside"><!-- 搜索栏 -->
<div id="search"><input class="search-input" type="text" placeholder="search"><icon id="search-icon" class="fa fa-bars" title="收起目录"></div>
<!-- 侧边目录栏 -->
<div id="tree">
</div><div id="toc"></div> 
<!-- 引入备案<footer id="footer"><a href="https://beian.miit.gov.cn" target="_blank">粤ICP备2024236103号</a></footer>--></aside>		<!-- 引入侧边栏-->
        <nav><div>
    <!-- 显示侧边栏 --><icon id="asideshow" class="fa fa-bars" title="显示侧边栏"></icon><ul id="menu">
    <!-- 内部链接本页面直接跳转 -->
    
    <li class="menu-item"><a href="/index.html" class="menu-item-link">主页</a></li>
    
    <li class="menu-item"><a href="/search/index.html" class="menu-item-link">搜索</a></li>
    
    <li class="menu-item"><a href="/Project/index.html" class="menu-item-link">技能</a></li>
    
    <li class="menu-item"><a href="/工具网站/index.html" class="menu-item-link">网站</a></li>
    
    <!-- 外部链接打开新的窗口跳转 -->
    
    <li class="menu-item"><a href="https://github.com/wodemingzihenchang" class="menu-item-link" target="_blank">github</a></li>
    <li class="menu-item"><a href="https://gitee.com/littleboy97" class="menu-item-link" target="_blank">gitee</a></li></ul>
</div></nav>	<!-- 引入导航 -->
        <div id="content"><div>
    <span id="post-author">作者: littleboy</span>
    <span id="post-date">2025-03-04 16:19:07</span>
</div>

<div id="article"><h1 id="Sw-编辑零部件属性"><a href="#Sw-编辑零部件属性" class="headerlink" title="Sw_编辑零部件属性"></a>Sw_编辑零部件属性</h1><p>当我们以还原的方式打开装配体时，其零部件也是有加载到程序内存里来的。按理是可以不用打开零部件再编辑零件的属性的。</p>
<p>通过object[] vComponents &#x3D; swAssy.GetComponents(false);获得零部件集合，</p>
<p>再遍历集合里的零部件，用 swCustPropMgr &#x3D; swCompModel.Extension.CustomPropertyManager[“”];去对属性进行编辑。</p>
<h2 id="代码"><a href="#代码" class="headerlink" title="代码"></a>代码</h2><figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">Prop</span>()</span></span><br><span class="line">        &#123;            </span><br><span class="line">            <span class="comment">// 获取当前活动的文档</span></span><br><span class="line">            AssemblyDoc swAssy = (AssemblyDoc)swApp.ActiveDoc; </span><br><span class="line">			CustomPropertyManager swCustPropMgr;</span><br><span class="line">            <span class="comment">// 写入属性之前，将装配体设定轻化到还原</span></span><br><span class="line">            swAssy.ResolveAllLightWeightComponents(<span class="literal">true</span>);</span><br><span class="line">            <span class="comment">// 获取零部件，true仅获取顶层组件，false是全部</span></span><br><span class="line">            <span class="built_in">object</span>[] vComponents = swAssy.GetComponents(<span class="literal">false</span>);</span><br><span class="line">            <span class="keyword">foreach</span> (<span class="built_in">object</span> SingleComponent <span class="keyword">in</span> vComponents)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="comment">// 获取零部件的自定义属性</span></span><br><span class="line">                Component2 swComponent = (Component2)SingleComponent; </span><br><span class="line">                ModelDoc2 swCompModel = swComponent.GetModelDoc2();</span><br><span class="line">                <span class="keyword">if</span> (swCompModel == <span class="literal">null</span>)</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="keyword">continue</span>;</span><br><span class="line">                &#125;</span><br><span class="line">                <span class="keyword">if</span> (swCompModel.GetType() == (<span class="built_in">int</span>)swDocumentTypes_e.swDocPART)</span><br><span class="line">                &#123;</span><br><span class="line">                    swCustPropMgr = swCompModel.Extension.CustomPropertyManager[<span class="string">&quot;&quot;</span>];</span><br><span class="line">                    swCustPropMgr.Add3(<span class="string">&quot;Length&quot;</span>, (<span class="built_in">int</span>)swCustomInfoType_e.swCustomInfoYesOrNo, <span class="string">&quot;X&quot;</span>, (<span class="built_in">int</span>)swCustomPropertyAddOption_e.swCustomPropertyDeleteAndAdd);</span><br><span class="line">                &#125;</span><br><span class="line">                <span class="keyword">else</span> <span class="keyword">if</span> (swCompModel.GetType() == (<span class="built_in">int</span>)swDocumentTypes_e.swDocASSEMBLY)</span><br><span class="line">                &#123;</span><br><span class="line">                    swCustPropMgr = swCompModel.Extension.CustomPropertyManager[<span class="string">&quot;&quot;</span>];</span><br><span class="line">                    swCustPropMgr.Add3(<span class="string">&quot;Length&quot;</span>, (<span class="built_in">int</span>)swCustomInfoType_e.swCustomInfoText, <span class="string">&quot;X&quot;</span>, (<span class="built_in">int</span>)swCustomPropertyAddOption_e.swCustomPropertyDeleteAndAdd);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br></pre></td></tr></table></figure>

</div>
 			<!-- 引入正文 -->
    </div>	
    
<script src="/lib/highlight/highlight.pack.js"></script>
<!-- 引入代码高亮的 js -->
    
<script src="/lib/jquery-3.4.1.min.js"></script>
	<!-- 引入 jquery -->
    
<script src="/lib/jquery.pjax.js"></script>
		<!-- 引入 pjax -->
    
<script src="/js/main.js"></script>
					<!-- 引入 js 文件 -->
	
<script src="/js/search.js"></script>
				<!-- 引入 js 文件 -->	
	<script type="text/javascript">      
     var search_path = "search.xml";
	 if (search_path.length == 0) {search_path = "search.xml";} var path = '/' + search_path;
     searchFunc(path, 'local-search-input', 'local-search-result');
	</script>

	<script type="module">import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs'; 
	mermaid.initialize({ theme: 'forest'});
	</script> <!-- 引入 mermaid 流程图 -->
</body></html>